version: 0.0
os: linux
files:
  - source: CalculatePi/CalculatePi.Web/build_output
    destination: /home/ec2-user/calculatepi
  - source: scripts/virtualhost.conf
    destination: /home/ec2-user/calculatepi
  - source: scripts/kestrel-aspnetcoreapp.service
    destination: /etc/systemd/system/
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root
      
# JWS: Not necessary to be run every time as the instance is setup already
#    - location: scripts/install_dotnetcore
#      timeout: 500
#      runas: root

#    - location: scripts/install_httpd
#      timeout: 300
#      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
