version: 0.2
phases:
  install:
     runtime-versions:
        dotnet: 2.2
  
  pre_build:
    commands:
      - pip install --upgrade awscli
      - dotnet restore CalculatePi/CalculatePi/CalculatePi.Library.csproj
      - dotnet restore CalculatePi/CalculatePi.Test/CalculatePi.Library.Test.csproj
      - dotnet restore CalculatePi/CalculatePi.CLI/CalculatePi.CLI.csproj
      - dotnet restore CalculatePi/CalculatePi.Web/CalculatePi.Web.csproj
  build:
    commands:
      - dotnet build -c release -o ./build_output CalculatePi/CalculatePi/CalculatePi.Library.csproj
      - dotnet build -c release -o ./test_output CalculatePi/CalculatePi.Test/CalculatePi.Library.Test.csproj
      - dotnet build -c release -o ./build_output CalculatePi/CalculatePi.CLI/CalculatePi.CLI.csproj
      - dotnet build -c release -o ./build_output CalculatePi/CalculatePi.Web/CalculatePi.Web.csproj

      - dotnet publish -c release -o ./build_output CalculatePi/CalculatePi.Web/CalculatePi.Web.csproj

      - dotnet vstest CalculatePi/CalculatePi.Test/test_output/CalculatePi.Library.Test.dll
  post_build:
    commands:

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  files:
    - template.yml
    - CalculatePi/CalculatePi.Web/build_output/**/*
    - scripts/**/*
    - appspec.yml
    - template-configuration.json
