#!/bin/bash
cd 〜

# use systemd to start and monitor dotnet application
systemctl enable kestrel-CalculatePi.service
systemctl start kestrel-CalculatePi.service

# start apache
systemctl restart httpd
