#!/bin/bash

export ASPNETCORE_ENVIRONMENT=Production

# use systemd to start and monitor dotnet application
systemctl enable kestrel-CalculatePi.service
systemctl start kestrel-CalculatePi.service

# start apache
systemctl restart httpd
